### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by Katamave** [Wired-Square/homeassistant-sma-sw#1]
When i try to add integration i get an error:

Der Konfigurationsfluss konnte nicht geladen werden: [object Object]

**Comment by garthberry** [comment]
The integration relies on the sma-query library at this location [sma-query](https://github.com/Wired-Square/sma-query), you will first need to install that into your python environment. This is a manual step at the moment, the plan is to submit that library to the pypi repository once stable. At that time the integration will be able to automatically resolve that dependency.

The sma-query library can be installed by cloning the repository onto the host running HomeAssistant, make sure you are using the same Python environment as HomeAssistant then from within the cloned repository run the following command

`python setup.py develop`

**Comment by garthberry** [comment]
The dependency has been uploaded to PyPi. Pull changes to homeassistant-sma-sw, after that the dependency should be automatically resolved by HomeAssistant without the need to follow the steps in the previous comment.

**Comment by garthberry** [comment]
Nice work, if you ever update the integration pulling a fresh copy should now work without the need to manually install the dependency.
