### ISSUE TITLE
HACS support?

### ISSUE THREAD

**Issue by Marck** [Wired-Square/homeassistant-sma-sw#3]
Hi!

Any change this code will get HACS support for easier installation? 
If not I could give it a go if requested

**Comment by aferrara** [comment]
Hi Marck,

I am in the process of creating an add-on to make this easier to install. I should have it done in the next few days.

**Comment by Marck** [comment]
Awesome, looking forward to it. I also created a integration around the code from here, see #4.
Just tested it and my inverter connects just fine (it does give a fault, but I guess that's because there is no sunlight atm)
